# Generated by Django 4.0 on 2021-12-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
