# Generated by Django 4.0 on 2021-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
