# Generated by Django 4.0 on 2021-12-15 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(blank=True, max_length=40)),
                ('product_unit', models.CharField(blank=True, max_length=40)),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_status', models.IntegerField(default=0)),
                ('other_details', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
